// <auto-generated />
using Mediatheque_DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mediatheque_DAL.Migrations
{
    [DbContext(typeof(MediaDbContext))]
    partial class MediaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Mediatheque_DAL.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("genre_name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("GenreName")
                        .IsUnique();

                    b.ToTable("Genres", (string)null);
                });

            modelBuilder.Entity("Mediatheque_DAL.Models.MediaGenre", b =>
                {
                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasColumnName("genre_id");

                    b.Property<int>("MediaId")
                        .HasColumnType("int")
                        .HasColumnName("media_id");

                    b.HasKey("GenreId", "MediaId");

                    b.HasIndex("MediaId");

                    b.ToTable("Media_Genres", (string)null);
                });

            modelBuilder.Entity("Mediatheque_DAL.Models.MediaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LengthMinutes")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("length_minutes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("type");

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("MediaItems", (string)null);
                });

            modelBuilder.Entity("Mediatheque_DAL.Models.MediaStatus", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("MediaId")
                        .HasColumnType("int")
                        .HasColumnName("media_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.HasKey("UserId", "MediaId");

                    b.HasIndex("MediaId");

                    b.ToTable("Media_Statuses", (string)null);
                });

            modelBuilder.Entity("Mediatheque_DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Mediatheque_DAL.Models.MediaGenre", b =>
                {
                    b.HasOne("Mediatheque_DAL.Models.Genre", "Genre")
                        .WithMany("MediaGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("genre_ibfk");

                    b.HasOne("Mediatheque_DAL.Models.MediaItem", "MediaItem")
                        .WithMany("MediaGenres")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("media_item_genre_ibfk");

                    b.Navigation("Genre");

                    b.Navigation("MediaItem");
                });

            modelBuilder.Entity("Mediatheque_DAL.Models.MediaStatus", b =>
                {
                    b.HasOne("Mediatheque_DAL.Models.MediaItem", "MediaItem")
                        .WithMany("MediaStatuses")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("media_item_status_ibfk");

                    b.HasOne("Mediatheque_DAL.Models.User", "User")
                        .WithMany("MediaStatuses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Status_user_ibfk");

                    b.Navigation("MediaItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mediatheque_DAL.Models.Genre", b =>
                {
                    b.Navigation("MediaGenres");
                });

            modelBuilder.Entity("Mediatheque_DAL.Models.MediaItem", b =>
                {
                    b.Navigation("MediaGenres");

                    b.Navigation("MediaStatuses");
                });

            modelBuilder.Entity("Mediatheque_DAL.Models.User", b =>
                {
                    b.Navigation("MediaStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
